### ISSUE TITLE
I updated adding webview for showing your website.

### ISSUE THREAD

**Issue by suhanlee** [SpencerAung/coronavirus-info#1]
![image](https://user-images.githubusercontent.com/2666166/73592739-a794ed00-4540-11ea-9217-26d7e783c071.png)

@SpencerAung How about discuss next item?

**Comment by suhanlee** [comment]
Repo is here. https://github.com/suhanlee/rn-coronavirus-info

**Comment by SpencerAung** [comment]
@suhanlee I am sorry I just noticed this issue now... I have added international news and Myanmar news sections. I have also made subtle design changes.
